// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// EstimateRho
double EstimateRho(const arma::vec& U, const arma::vec& V, const arma::vec& W);
RcppExport SEXP _CItest_EstimateRho(SEXP USEXP, SEXP VSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(EstimateRho(U, V, W));
    return rcpp_result_gen;
END_RCPP
}
// CITestStat
arma::vec CITestStat(const arma::mat& X, const arma::vec& Y, const arma::vec& Z, const double& h);
RcppExport SEXP _CItest_CITestStat(SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const double& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(CITestStat(X, Y, Z, h));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CItest_EstimateRho", (DL_FUNC) &_CItest_EstimateRho, 3},
    {"_CItest_CITestStat", (DL_FUNC) &_CItest_CITestStat, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_CItest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
