# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimate rho
#'
#' @param U A vector of U
#' @param V A vector of V
#' @param W A vector of W
#' @export
EstimateRho <- function(U, V, W) {
    .Call(`_CItest_EstimateRho`, U, V, W)
}

#' Estimate the CI test statistics
#'
#' @param X A matrix of covariates
#' @param Y A vector of response
#' @param Z A vector of conditional variable
#' @param h kernel bandwidth
#' @export
CITestStat <- function(X, Y, Z, h) {
    .Call(`_CItest_CITestStat`, X, Y, Z, h)
}

